use std::fmt::Write as _;

use anyhow::{Context, Result, bail};
use bytemuck::{Pod, Zeroable};

use crate::protocol::{
    BAD_REQUEST_BODY, GPU_HELLO_BODY, GPU_ROOT_BODY, HEALTH_BODY, METHOD_NOT_ALLOWED_BODY,
    NOT_FOUND_BODY, UTF8_BODY,
};

#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
pub(super) struct StringMeta {
    pub byte_offset: u32,
    pub byte_len: u32,
    pub scalar_len: u32,
    pub _padding: u32,
}

#[derive(Debug)]
pub(super) struct ShaderAssets {
    pub source: String,
    pub metadata: Vec<StringMeta>,
    pub words: Vec<u32>,
    pub byte_len: usize,
}

#[derive(Debug, Clone, Copy)]
struct StringDefinition {
    wgsl_name: &'static str,
    value: &'static str,
}

const STRING_DEFINITIONS: &[StringDefinition] = &[
    StringDefinition {
        wgsl_name: "STRING_HTTP_VERSION",
        value: "HTTP/1.1 ",
    },
    StringDefinition {
        wgsl_name: "STRING_HEADER_CONTENT_TYPE",
        value: "\r\nContent-Type: ",
    },
    StringDefinition {
        wgsl_name: "STRING_HEADER_CONTENT_LENGTH",
        value: "\r\nContent-Length: ",
    },
    StringDefinition {
        wgsl_name: "STRING_HEADER_TAIL",
        value: "\r\nConnection: close\r\nServer: gput\r\nX-Gput-Backend: gpu\r\n\r\n",
    },
    StringDefinition {
        wgsl_name: "STRING_STATUS_OK",
        value: "200 OK",
    },
    StringDefinition {
        wgsl_name: "STRING_STATUS_BAD_REQUEST",
        value: "400 Bad Request",
    },
    StringDefinition {
        wgsl_name: "STRING_STATUS_NOT_FOUND",
        value: "404 Not Found",
    },
    StringDefinition {
        wgsl_name: "STRING_STATUS_METHOD_NOT_ALLOWED",
        value: "405 Method Not Allowed",
    },
    StringDefinition {
        wgsl_name: "STRING_CONTENT_TYPE_JSON",
        value: "application/json",
    },
    StringDefinition {
        wgsl_name: "STRING_CONTENT_TYPE_TEXT",
        value: "text/plain; charset=utf-8",
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_ROOT",
        value: GPU_ROOT_BODY,
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_HEALTH",
        value: HEALTH_BODY,
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_HELLO",
        value: GPU_HELLO_BODY,
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_BAD_REQUEST",
        value: BAD_REQUEST_BODY,
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_METHOD_NOT_ALLOWED",
        value: METHOD_NOT_ALLOWED_BODY,
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_NOT_FOUND",
        value: NOT_FOUND_BODY,
    },
    StringDefinition {
        wgsl_name: "STRING_BODY_UTF8",
        value: UTF8_BODY,
    },
];

pub(super) fn build_shader_assets(shader_body: &str) -> Result<ShaderAssets> {
    let mut bytes = Vec::new();
    let mut metadata = Vec::with_capacity(STRING_DEFINITIONS.len());
    let mut source = String::with_capacity(shader_body.len() + STRING_DEFINITIONS.len() * 48);

    source.push_str("// String IDs generated by Rust. The bytes live in GPU storage buffers.\n");

    for (index, definition) in STRING_DEFINITIONS.iter().enumerate() {
        validate_wgsl_identifier(definition.wgsl_name)?;

        let byte_offset = u32::try_from(bytes.len())
            .with_context(|| format!("{} byte offset does not fit u32", definition.wgsl_name))?;
        let byte_len = u32::try_from(definition.value.len())
            .with_context(|| format!("{} byte length does not fit u32", definition.wgsl_name))?;
        let scalar_len = u32::try_from(definition.value.chars().count())
            .with_context(|| format!("{} scalar length does not fit u32", definition.wgsl_name))?;

        metadata.push(StringMeta {
            byte_offset,
            byte_len,
            scalar_len,
            _padding: 0,
        });
        bytes.extend_from_slice(definition.value.as_bytes());

        writeln!(source, "const {}: u32 = {index}u;", definition.wgsl_name)
            .expect("writing to a String cannot fail");
    }

    source.push('\n');
    source.push_str(shader_body);

    Ok(ShaderAssets {
        source,
        metadata,
        words: pack_bytes(&bytes),
        byte_len: bytes.len(),
    })
}

fn validate_wgsl_identifier(identifier: &str) -> Result<()> {
    let mut bytes = identifier.bytes();
    let Some(first) = bytes.next() else {
        bail!("WGSL string identifier cannot be empty");
    };

    if !(first == b'_' || first.is_ascii_alphabetic())
        || bytes.any(|byte| !(byte == b'_' || byte.is_ascii_alphanumeric()))
    {
        bail!("invalid WGSL string identifier {identifier:?}");
    }

    Ok(())
}

fn pack_bytes(bytes: &[u8]) -> Vec<u32> {
    let mut words = vec![0_u32; bytes.len().div_ceil(4)];

    for (byte_index, byte) in bytes.iter().copied().enumerate() {
        let word_index = byte_index / 4;
        let shift = (byte_index % 4) * 8;
        words[word_index] |= u32::from(byte) << shift;
    }

    words
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arena_round_trips_unaligned_unicode_strings() {
        let assets = build_shader_assets("fn placeholder() {}\n").expect("assets build");
        let utf8_index = STRING_DEFINITIONS
            .iter()
            .position(|definition| definition.wgsl_name == "STRING_BODY_UTF8")
            .expect("UTF-8 body definition");
        let meta = assets.metadata[utf8_index];
        let mut unpacked = Vec::with_capacity(meta.byte_len as usize);

        for relative_index in 0..meta.byte_len as usize {
            let absolute_index = meta.byte_offset as usize + relative_index;
            let word = assets.words[absolute_index / 4];
            unpacked.push(((word >> ((absolute_index % 4) * 8)) & 0xff) as u8);
        }

        assert_eq!(unpacked, UTF8_BODY.as_bytes());
        assert_eq!(meta.scalar_len as usize, UTF8_BODY.chars().count());
    }

    #[test]
    fn generated_ids_match_definition_order() {
        let assets = build_shader_assets("").expect("assets build");

        for (index, definition) in STRING_DEFINITIONS.iter().enumerate() {
            assert!(
                assets
                    .source
                    .contains(&format!("const {}: u32 = {index}u;", definition.wgsl_name))
            );
        }
    }
}
