use std::fmt::Write as _;

use anyhow::{Context, Result};
use bytemuck::{Pod, Zeroable};

use crate::router::{
    BODY_OP_BACKEND, BODY_OP_BACKEND_VARIANT, BODY_OP_LITERAL, BODY_OP_PATH, BODY_OP_PATH_HASH,
    BODY_OP_QUERY, BODY_OP_REQUEST_BYTES, BODY_OP_WORDS, CompiledRouter, RESPONSE_DESCRIPTOR_WORDS,
    ROUTE_STRIDE_WORDS,
};

#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
pub(super) struct StringMeta {
    pub byte_offset: u32,
    pub byte_len: u32,
    pub scalar_len: u32,
    pub _padding: u32,
}

#[derive(Debug)]
pub(super) struct ShaderAssets {
    pub source: String,
    pub metadata: Vec<StringMeta>,
    pub words: Vec<u32>,
    pub byte_len: usize,
}

pub(super) fn build_shader_assets(
    shader_body: &str,
    router: &CompiledRouter,
) -> Result<ShaderAssets> {
    let mut bytes = Vec::new();
    let mut metadata = Vec::with_capacity(router.strings().len());

    for (index, value) in router.strings().iter().enumerate() {
        let byte_offset = u32::try_from(bytes.len())
            .with_context(|| format!("shader string {index} byte offset does not fit u32"))?;
        let byte_len = u32::try_from(value.len())
            .with_context(|| format!("shader string {index} byte length does not fit u32"))?;
        let scalar_len = u32::try_from(value.chars().count())
            .with_context(|| format!("shader string {index} scalar length does not fit u32"))?;

        metadata.push(StringMeta {
            byte_offset,
            byte_len,
            scalar_len,
            _padding: 0,
        });
        bytes.extend_from_slice(value.as_bytes());
    }

    let ids = router.shader_string_ids();
    let mut source = String::with_capacity(shader_body.len() + 1_024);
    source.push_str("// Router constants generated by Rust. Data lives in GPU storage buffers.\n");
    writeln!(
        source,
        "const STRING_HTTP_VERSION: u32 = {}u;",
        ids.http_version
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const STRING_HEADER_CONTENT_TYPE: u32 = {}u;",
        ids.header_content_type
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const STRING_HEADER_CONTENT_LENGTH: u32 = {}u;",
        ids.header_content_length
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const STRING_HEADER_TAIL: u32 = {}u;",
        ids.header_tail
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const STRING_BACKEND_GPU: u32 = {}u;",
        ids.backend_gpu
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const ROUTE_STRIDE_WORDS: u32 = {ROUTE_STRIDE_WORDS}u;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const RESPONSE_DESCRIPTOR_WORDS: u32 = {RESPONSE_DESCRIPTOR_WORDS}u;"
    )
    .expect("writing to a String cannot fail");
    writeln!(source, "const BODY_OP_WORDS: u32 = {BODY_OP_WORDS}u;")
        .expect("writing to a String cannot fail");
    writeln!(source, "const BODY_OP_LITERAL: u32 = {BODY_OP_LITERAL}u;")
        .expect("writing to a String cannot fail");
    writeln!(source, "const BODY_OP_PATH: u32 = {BODY_OP_PATH}u;")
        .expect("writing to a String cannot fail");
    writeln!(source, "const BODY_OP_QUERY: u32 = {BODY_OP_QUERY}u;")
        .expect("writing to a String cannot fail");
    writeln!(source, "const BODY_OP_BACKEND: u32 = {BODY_OP_BACKEND}u;")
        .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const BODY_OP_REQUEST_BYTES: u32 = {BODY_OP_REQUEST_BYTES}u;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const BODY_OP_PATH_HASH: u32 = {BODY_OP_PATH_HASH}u;"
    )
    .expect("writing to a String cannot fail");
    writeln!(
        source,
        "const BODY_OP_BACKEND_VARIANT: u32 = {BODY_OP_BACKEND_VARIANT}u;"
    )
    .expect("writing to a String cannot fail");
    source.push('\n');
    source.push_str(shader_body);

    Ok(ShaderAssets {
        source,
        metadata,
        words: pack_bytes(&bytes),
        byte_len: bytes.len(),
    })
}

fn pack_bytes(bytes: &[u8]) -> Vec<u32> {
    let mut words = vec![0_u32; bytes.len().div_ceil(4)];

    for (byte_index, byte) in bytes.iter().copied().enumerate() {
        let word_index = byte_index / 4;
        let shift = (byte_index % 4) * 8;
        words[word_index] |= u32::from(byte) << shift;
    }

    words
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{builtin_router, protocol::UTF8_BODY};

    #[test]
    fn arena_round_trips_unaligned_unicode_strings() {
        let router = builtin_router().compile().expect("router compiles");
        let assets = build_shader_assets("fn placeholder() {}\n", &router).expect("assets build");
        let utf8_index = router
            .strings()
            .iter()
            .position(|value| value == UTF8_BODY)
            .expect("UTF-8 body definition");
        let meta = assets.metadata[utf8_index];
        let mut unpacked = Vec::with_capacity(meta.byte_len as usize);

        for relative_index in 0..meta.byte_len as usize {
            let absolute_index = meta.byte_offset as usize + relative_index;
            let word = assets.words[absolute_index / 4];
            unpacked.push(((word >> ((absolute_index % 4) * 8)) & 0xff) as u8);
        }

        assert_eq!(unpacked, UTF8_BODY.as_bytes());
        assert_eq!(meta.scalar_len as usize, UTF8_BODY.chars().count());
    }

    #[test]
    fn generated_source_contains_router_bytecode_contract() {
        let router = builtin_router().compile().expect("router compiles");
        let assets = build_shader_assets("", &router).expect("assets build");

        assert!(assets.source.contains("const BODY_OP_PATH_HASH: u32 = 5u;"));
        assert!(
            assets
                .source
                .contains("const ROUTE_STRIDE_WORDS: u32 = 4u;")
        );
    }
}
